#Use the official Python image from the Docker Hub
From python:3.9-slim

#Set the working directory in the container
workdir /app

#Copy the current directory contents into the container at /app
copy . /app

#Install any needed packages specified in requirements.txt
run pip install flask

#Make port 5000 available to the world outside this container
expose 5000

#Define environment variable
CMD ["python", "app.py"]